version: '3.7'

services:
  proxy:
    image: nginx:1.19.6-alpine
    container_name: stakenet-explorer-proxy
    ports:
      - '80:80'
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped
    networks:
      - backend-network
      - frontend-network
    depends_on:
      - frontend
      - server

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: stakenet-explorer-frontend
    restart: unless-stopped
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend-network
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: stakenet-explorer-server
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - REDIS_HOST=redis
      - RABBITMQ_HOST=${RABBITMQ_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgresql
      - POSTGRES_DB=${POSTGRES_DB}
    restart: unless-stopped
    networks:
      - backend-network
    depends_on:
      - postgresql
      - redis
      - wallet

  postgresql:
    image: postgres:13.1-alpine
    container_name: stakenet-explorer-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - backend-network

  redis:
    image: redis:6.0.10-alpine
    container_name: stakenet-explorer-redis
    command: redis-server
    volumes:
      - redis-data:/var/lib/redis/data
    restart: unless-stopped
    networks:
      - backend-network

  wallet:
    build:
      context: ./wallet
      dockerfile: Dockerfile
    container_name: stakenet-explorer-wallet
    restart: unless-stopped
    volumes:
      - wallet-data:/root/.xsncore
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
  frontend-network:
    driver: bridge

volumes:
  redis-data:
  database-data:
  wallet-data:
